PUT Endpoint
jeethsoni/movies-rest-api pull request #8
Opened 2023-12-04 22:32 UTC by jeethsoni

Added `PUT` blueprint and service to update a record by `movie_id`

2023-12-04 23:37 UTC, riteshapatel commented on blueprints/movie/blueprint.py
> +    pk = movie_id
Why this?

2023-12-04 23:39 UTC, riteshapatel requested changes

2023-12-04 23:39 UTC, riteshapatel commented on blueprints/movie/blueprint.py
> +    result = svc_put(payload, pk)
Pk can be straight up movie_id no?

2023-12-04 23:39 UTC, riteshapatel commented on blueprints/movie/service.py
> +    sql = f"UPDATE {SCHEMA_NAME}.{MOVIE} SET title = %(title)s, description = %(description)s, movie_year = %(movie_year)s, rating = %(rating)s, runtime = %(runtime)s, votes = %(votes)s, revenue = %(
Format SQL properly so it’s readable

2023-12-04 23:39 UTC, riteshapatel commented on blueprints/movie/service.py
> +    params = {"title": title, "description": description, "movie_year": year, "rating": rating, "runtime": runtime, "votes": votes, "revenue": revenue, "metascore": metascore, "created_at": created_a
Why dictionary is not prettified? Make it readable. VScode can format it for ya! Or use jsonlint to format it. Google it.

2023-12-04 23:40 UTC, jeethsoni commented on blueprints/movie/blueprint.py
> +    pk = movie_id
pk = movie?

2023-12-06 01:04 UTC, riteshapatel commented on blueprints/movie/service.py
> +        """
☝️ Remove these comments. SQL as a comment?  Also where are you executing this SQL? Code is wrong.

2023-12-06 01:09 UTC, riteshapatel commented on blueprints/movie/service.py
> +    print(result)
Remove `print` statements before you push. These `print` statements would make it into `production`. Not good.

2023-12-06 01:10 UTC, riteshapatel requested changes
Sending back for changes.

2023-12-08 18:53 UTC, riteshapatel approved these changes

2023-12-08 18:53 UTC, merged